apiVersion: v1
kind: Pod
metadata:
  name: mydb
  labels:
    name: mydb
    tier: database
spec:
  containers:
    - name: mydb
      image: mysql:latest
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password